routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('index');

Route::get("registro", 'Registro@index')->name('register');
Route::post("registro", 'Registro@save')->name('register-save');


Route::get("login", 'Registro@login')->name('login');

Route::get('/terminos-y-condiciones', function () {
    $filename="POLITICA DE TRATAMIENTO DE LA INFORMACIÓN Y TERMINOS Y CONDICIONES DEL SERVICIO.pdf";

    return response()->file((__DIR__.'/../public/'.$filename), [
        'Content-Type' => 'application/pdf',
        'Content-Disposition' => 'inline; filename="'.$filename.'"'
    ]);
})->name('terminos-condiciones');

Route::middleware("auth")->get("nuevo-analisis", 'FilesController@newFile')->name('newFile');
Route::middleware("auth")->post("nuevo-analisis", 'FilesController@saveFile')->name('saveFile');
Route::middleware("auth")->post("eliminar-analisis/concreto/{id}", 'FilesController@destroy')->name('deleteFile');

Route::middleware("auth")->get("mis-analisis", 'FilesController@indexMult')->name('myFiles');
Route::get("mis-analisis/concreto/{id}", 'FilesController@show')->name('myFile');
Route::middleware("auth")->get("mis-analisis/concreto/editar/{id}", 'FilesController@edit')->name('editFile');
Route::post("mis-analisis/concreto/update/{id}", 'FilesController@update')->name('updateFile');

Route::get("mis-analisis/abstracto/{id}", 'ControlAbstracto@show')->name('myFileAbstracto');
Route::get("mis-analisis/abstracto/editar/{id}", 'ControlAbstracto@edit')->name('editFileAbstracto');
Route::post("mis-analisis/abstracto/update/{id}", 'ControlAbstracto@update')->name('updateFileAbstracto');

Route::post("eliminar-analisis/abstracto/{id}", 'ControlAbstracto@destroy')->name('deleteFileAbstracto');

Route::get("buscar", 'FilesController@search')->name('searchFile');
Route::get("export/excel", 'FilesController@exportExcel')->name('export.excel');
Route::get("export/word", 'FilesController@exportWord')->name('export.word');
Route::middleware("auth")->get("star/concreto", 'FilesController@star')->name('starC');
Route::middleware("auth")->get("star/abstracto", 'ControlAbstracto@star')->name('starA');

Route::resource('abstracto', 'ControlAbstracto');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
    
    Route::post('login', '\App\Http\Controllers\VoyagerAuthController@postLogin')->name('voyager.postlogin');
    
    Route::post('logout', function(){
        Auth::logout();
        return redirect()->route('index');
    })->name('voyager.logout');
    
    Route::get('logout', function(){
        Auth::logout();
        return redirect()->route('index');
    })->name('voyager.logoutG');
    
    Route::get('users-excel', function(){
        $users = \App\User::where("id", '>', 0);
        return (new \App\Exports\ExportUsers($users))->download('usuarios.xlsx', \Maatwebsite\Excel\Excel::XLSX);
    })->name('users.excel');
    Route::get('users-csv', function(){
        $users = \App\User::where("id", '>', 0);
        return (new \App\Exports\ExportUsers($users))->download('usuarios.csv', \Maatwebsite\Excel\Excel::CSV);
    })->name('users.csv');

});

Route::get('logout', function(){
        Auth::logout();
        return redirect()->route('index');
})->name('voyager.logoutG2');



Route::get('/home', function(){
  return  redirect()->route('myFiles');
})->name('home');

app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class File extends Model
{
    
}

app/Http/Controllers/FilesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Events\BreadDataAdded;
use TCG\Voyager\Events\BreadDataDeleted;
use TCG\Voyager\Events\BreadDataRestored;
use TCG\Voyager\Events\BreadDataUpdated;
use TCG\Voyager\Events\BreadImagesDeleted;
use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use TCG\Voyager\Database\Schema\SchemaManager;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Exports\ExportExcel;

class FilesController extends \TCG\Voyager\Http\Controllers\Controller
{
    
    use BreadRelationshipParser;
    
    public function indexMult(Request $request){
        
         $title = 'Fichas creadas';
         
         $types = \App\TypeProcess::all();
        $authorities = \App\Authority::all();
        $decisions = \App\DecisionType::all();
        
        $dRow = \App\DataRow::where('data_type_id', 6)->where('field', 'decision_type_id')->first();
         if($dRow){
             $decisionAbs = \json_decode($dRow->details, true);
         }else{
             $decisionAbs['options'] = [];
         }
         
        $dRow = \App\DataRow::where('data_type_id', 6)->where('field', 'authority_id')->first();
         if($dRow){
             $authorityAbs = \json_decode($dRow->details, true);
         }else{
             $authorityAbs['options'] = [];
         }
         
         $jDecision = [];
         foreach($decisions as $decision){
            $jDecision['concreto'][$decision->id] = $decision->name; 
         }
         
         foreach ($decisionAbs['options'] as $id=>$decision){
             $jDecision['abstracto'][$id] = $decision;
         }
         
         $jDecision = json_encode($jDecision);
         
         $queryC = \App\File::where('created_by', auth()->user()->id)
                   ->select(DB::raw('id,
                                    name,
                                    type_control,
                                    view,
                                    authority_id,
                                    magistrate,
                                    decision_type_id,
                                    judgment,
                                    created_at'))
                   ->orderBy('created_at', 'desc');
         
         $query = \App\FilesAbstract::where('created_by', auth()->user()->id)
                    ->select(DB::raw('id,
                                    name,
                                    type_control,
                                    view,
                                    authority_id,
                                    magistrate,
                                    decision_type_id,
                                    judgment,
                                    created_at'))
                   ->orderBy('created_at', 'desc')
                    ;
         
         $qs=[];
         if(isset($request->type) && $request->type == "1"){
             $queryC->where('type_control', 'c');
             $query->where('type_control', 'c');
             $qs[]="type=".$request->type;
         }
         if(isset($request->type) && $request->type == "2"){
             $queryC->where('type_control', 'a');
             $query->where('type_control', 'a');
             $qs[]="type=".$request->type;
         }
         if(isset($request->authority) && $request->authority != ""){
             $queryC->where('authority_id', $request->authority);
             $query->where('authority_id', $request->authority);
             $qs[]="authority=".$request->authority;
         }
         if(isset($request->magistrate) && $request->magistrate != ""){
             $queryC->whereRaw('lower(magistrate) like \'%'.strtolower($request->magistrate).'%\'');
             $query->whereRaw('lower(magistrate) like \'%'.strtolower($request->magistrate).'%\'');
             $qs[]="magistrate=".$request->magistrate;
         }
         if(isset($request->judgment) && $request->judgment != ""){
             $queryC->where('judgment', $request->judgment);
             $query->where('judgment', $request->judgment);
             $qs[]="judgment=".$request->judgment;
         }
         if(isset($request->search) && $request->search != ""){
             
             $qs[]="search=".$request->search;
             
            $queryC->where(function($q1) use($request){
                $columns = ['name', 'judgment', 'magistrate', 'topic', 'actuator', 'actuated', 'acts', 'problem', 'answer', 'ratio_decidendi', 'content_decision'];
                foreach($columns as $column){
                    $q1->orWhereRaw('lower('.$column.') like \'%'.strtolower($request->search).'%\'');
                }
            });
            
            $query->where(function($q2)use($request){
                $columns = ['name', 'judgment', 'magistrate', 'topic', 'actuator', 'law', 'problem', 'answer', 'ratio_decidendi', 'content_decision', 'obiter_dicta'];
                foreach($columns as $column){
                    $q2->orWhereRaw('lower('.$column.') like \'%'.strtolower($request->search).'%\'');
                }
            });
         }
          $query->unionAll($queryC);
         $q = $query->toSql();
         
         $query = $t = DB::table( DB::raw(" ( $q ) t") )
                 ->mergeBindings($query->getQuery())
                 ->orderBy('created_at', 'desc')->paginate(20);
         
         $total = $t->count();
         
         if(isset($request->page)){
             $from = ($request->page*20)+1;
             $to = ($total*$request->page)+1;
         }else{
             $from = $total ? 1 : 0;
             $to = $total;
         }
         
         $dRow = \App\DataRow::where('data_type_id', 6)->where('field', 'authority_id')->first();
         if($dRow){
             $authority = \json_decode($dRow->details);
         }else{
             $authority = [];
         }
         
         $dRow = \App\DataRow::where('data_type_id', 6)->where('field', 'decision_type_id')->first();
         if($dRow){
             $decision = \json_decode($dRow->details);
         }else{
             $decision = [];
         }
         
         $actionsLst = [\App\Actions\ViewAction::class, \App\Actions\DeleteAction::class, \App\Actions\EditAction::class, \App\Actions\ViewSearchExcelAction::class, \App\Actions\ViewSearchWordAction::class];
        
        $dataType = Voyager::model('DataType')->where('slug', '=', 'files')->first();
         
        // Actions
        $actions = [];
        if (!empty($query)) {
            foreach ($actionsLst as $action) {
                $action = new $action($dataType, null);

                if ($action->shouldActionDisplayOnDataType()) {
                    $actions[] = $action;
                }
            }
        }
        
        $dataType1 = Voyager::model('DataType')->where('slug', '=', 'files')->first();
        $dataType2 = Voyager::model('DataType')->where('slug', '=', 'files-abstract')->first();
        
        $qExport = implode("&", $qs);
      
        return Voyager::view('files.index', compact(
            'title', 
                'query', 
                'total', 
                'types', 
                'authorities', 
                'decisions', 
                'decisionAbs', 
                'authorityAbs', 
                'jDecision', 
                'to', 'from', 'authority', 'decision', 'actions', 'dataType1', 'dataType2', 'qExport', 'request'
        ));
        
    }
    
    public function index(Request $request){
                // GET THE SLUG, ex. 'posts', 'pages', etc.
        $slug = 'files';

        // GET THE DataType based on the slug
        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Check permission
        $this->authorize('browse', app($dataType->model_name));

        $getter = $dataType->server_side ? 'paginate' : 'get';

        $search = (object) ['value' => $request->get('s'), 'key' => $request->get('key'), 'filter' => $request->get('filter')];

        $searchNames = [];
        if ($dataType->server_side) {
            $searchable = SchemaManager::describeTable(app($dataType->model_name)->getTable())->pluck('name')->toArray();
            $dataRow = Voyager::model('DataRow')->whereDataTypeId($dataType->id)->get();
            foreach ($searchable as $key => $value) {
                
                if(in_array($key, ['id', 'updated_at', 'deleted_at', 'created_by'])){
                    continue;
                }
                
                $field = $dataRow->where('field', $value)->first();
                $displayName = ucwords(str_replace('_', ' ', $value));
                if ($field !== null) {
                    $displayName = $field->getTranslatedAttribute('display_name');
                }
                $searchNames[$value] = $displayName;
            }
        }

        $orderBy = $request->get('order_by', $dataType->order_column);
        $sortOrder = $request->get('sort_order', $dataType->order_direction);
        $usesSoftDeletes = false;
        $showSoftDeleted = false;

        // Next Get or Paginate the actual content from the MODEL that corresponds to the slug DataType
        if (strlen($dataType->model_name) != 0) {
            $model = app($dataType->model_name);

            if ($dataType->scope && $dataType->scope != '' && method_exists($model, 'scope'.ucfirst($dataType->scope))) {
                $query = $model->{$dataType->scope}();
            } else {
                $query = $model::select('*');
            }

            // Use withTrashed() if model uses SoftDeletes and if toggle is selected
            if ($model && in_array(SoftDeletes::class, class_uses_recursive($model)) && Auth::user()->can('delete', app($dataType->model_name))) {
                $usesSoftDeletes = true;

resources/views/files/edit-add-a.blade.php
@php
    $edit = !is_null($dataTypeContentAbstract->getKey());
    $add  = is_null($dataTypeContentAbstract->getKey());
@endphp


    <div class="page-content edit-add container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="panel panel-bordered">
                    <!-- form start -->
                    <form role="form"
                            class="form-edit-add"
                            action="{{ $edit ? route('updateFile', $dataTypeContentAbstract->getKey()) : route('abstracto.store') }}"
                            method="POST" enctype="multipart/form-data">
                        <!-- PUT Method if we are editing -->
                        <!-- CSRF TOKEN -->
                        {{ csrf_field() }}

                        <div class="panel-body">

                            

                            <!-- Adding / Editing -->
                            @php
                                $dataTypeRows = $dataTypeAbstract->{($edit ? 'editRows' : 'addRows' )};
                            @endphp

                            @foreach($dataTypeRows as $row)
                                <!-- GET THE DISPLAY OPTIONS -->
                                @php
                                    $display_options = $row->details->display ?? NULL;
                                    if ($dataTypeContentAbstract->{$row->field.'_'.($edit ? 'edit' : 'add')}) {
                                        $dataTypeContentAbstract->{$row->field} = $dataTypeContentAbstract->{$row->field.'_'.($edit ? 'edit' : 'add')};
                                    }
                                @endphp
                                @if (isset($row->details->legend) && isset($row->details->legend->text))
                                    <legend class="text-{{ $row->details->legend->align ?? 'center' }}" style="background-color: {{ $row->details->legend->bgcolor ?? '#f0f0f0' }};padding: 5px;">{{ $row->details->legend->text }}</legend>
                                @endif

                                <div class="form-group @if($row->type == 'hidden') hidden @endif col-md-{{ $display_options->width ?? 12 }} {{ $errors->has($row->field) ? 'has-error' : '' }}" @if(isset($display_options->id)){{ "id=$display_options->id" }}@endif>
                                    {{ $row->slugify }}
                                    <label class="control-label" for="name">{{ $row->getTranslatedAttribute('display_name') }}</label>
                                    @include('voyager::multilingual.input-hidden-bread-edit-add')
                                    @if (isset($row->details->view))
                                        @include($row->details->view, ['row' => $row, 'dataType' => $dataType, 'dataTypeContent' => $dataTypeContent, 'content' => $dataTypeContentAbstract->{$row->field}, 'action' => ($edit ? 'edit' : 'add'), 'view' => ($edit ? 'edit' : 'add'), 'options' => $row->details])
                                    @elseif ($row->type == 'relationship')
                                        @include('voyager::formfields.relationship', ['options' => $row->details])
                                    @else
                                        {!! app('voyager')->formField($row, $dataType, $dataTypeContent) !!}
                                    @endif

                                    @foreach (app('voyager')->afterFormFields($row, $dataType, $dataTypeContent) as $after)
                                        {!! $after->handle($row, $dataType, $dataTypeContent) !!}
                                    @endforeach
                                    @if ($errors->has($row->field))
                                        @foreach ($errors->get($row->field) as $error)
                                            <span class="help-block">{{ $error }}</span>
                                        @endforeach
                                    @endif
                                </div>
                            @endforeach

                        </div><!-- panel-body -->

                        <div class="panel-footer">
                            @section('submit-buttons')
                                <button type="submit" class="btn btn-primary save">{{ __('voyager::generic.save') }}</button>
                            @stop
                            @yield('submit-buttons')
                        </div>
                    </form>

                    <iframe id="form_target" name="form_target" style="display:none"></iframe>
                    <form id="my_form" action="{{ route('voyager.upload') }}" target="form_target" method="post"
                            enctype="multipart/form-data" style="width:0;height:0;overflow:hidden">
                        <input name="image" id="upload_file" type="file"
                                 onchange="$('#my_form').submit();this.value='';">
                        <input type="hidden" name="type_slug" id="type_slug" value="{{ $dataTypeAbstract->slug }}">
                        {{ csrf_field() }}
                    </form>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-danger" id="confirm_delete_modal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><i class="voyager-warning"></i> {{ __('voyager::generic.are_you_sure') }}</h4>
                </div>

                <div class="modal-body">
                    <h4>{{ __('voyager::generic.are_you_sure_delete') }} '<span class="confirm_delete_name"></span>'</h4>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{ __('voyager::generic.cancel') }}</button>
                    <button type="button" class="btn btn-danger" id="confirm_delete">{{ __('voyager::generic.delete_confirm') }}</button>
                </div>
            </div>
        </div>
    </div>
    <!-- End Delete File Modal -->

resources/views/files/edit-add.blade.php
@php
    $edit = !is_null($dataTypeContent->getKey());
    $add  = is_null($dataTypeContent->getKey());
@endphp


    <div class="page-content edit-add container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="panel panel-bordered">
                    <!-- form start -->
                    <form role="form"
                            class="form-edit-add"
                            action="{{ $edit ? route('updateFile', $dataTypeContent->getKey()) : route('saveFile') }}"
                            method="POST" enctype="multipart/form-data">
                        <!-- PUT Method if we are editing -->
                        <!-- CSRF TOKEN -->
                        {{ csrf_field() }}

                        <div class="panel-body">

                            

                            <!-- Adding / Editing -->
                            @php
                                $dataTypeRows = $dataType->{($edit ? 'editRows' : 'addRows' )};
                            @endphp

                            @foreach($dataTypeRows as $row)
                                <!-- GET THE DISPLAY OPTIONS -->
                                @php
                                    $display_options = $row->details->display ?? NULL;
                                    if ($dataTypeContent->{$row->field.'_'.($edit ? 'edit' : 'add')}) {
                                        $dataTypeContent->{$row->field} = $dataTypeContent->{$row->field.'_'.($edit ? 'edit' : 'add')};
                                    }
                                @endphp
                                @if (isset($row->details->legend) && isset($row->details->legend->text))
                                    <legend class="text-{{ $row->details->legend->align ?? 'center' }}" style="background-color: {{ $row->details->legend->bgcolor ?? '#f0f0f0' }};padding: 5px;">{{ $row->details->legend->text }}</legend>
                                @endif

                                <div class="form-group @if($row->type == 'hidden') hidden @endif col-md-{{ $display_options->width ?? 12 }} {{ $errors->has($row->field) ? 'has-error' : '' }}" @if(isset($display_options->id)){{ "id=$display_options->id" }}@endif>
                                    {{ $row->slugify }}
                                    <label class="control-label" for="name">{{ $row->getTranslatedAttribute('display_name') }}</label>
                                    @include('voyager::multilingual.input-hidden-bread-edit-add')
                                    @if (isset($row->details->view))
                                        @include($row->details->view, ['row' => $row, 'dataType' => $dataType, 'dataTypeContent' => $dataTypeContent, 'content' => $dataTypeContent->{$row->field}, 'action' => ($edit ? 'edit' : 'add'), 'view' => ($edit ? 'edit' : 'add'), 'options' => $row->details])
                                    @elseif ($row->type == 'relationship')
                                        @include('voyager::formfields.relationship', ['options' => $row->details])
                                    @else
                                        {!! app('voyager')->formField($row, $dataType, $dataTypeContent) !!}
                                    @endif

                                    @foreach (app('voyager')->afterFormFields($row, $dataType, $dataTypeContent) as $after)
                                        {!! $after->handle($row, $dataType, $dataTypeContent) !!}
                                    @endforeach
                                    @if ($errors->has($row->field))
                                        @foreach ($errors->get($row->field) as $error)
                                            <span class="help-block">{{ $error }}</span>
                                        @endforeach
                                    @endif
                                </div>
                            @endforeach

                        </div><!-- panel-body -->

                        <div class="panel-footer">
                            @section('submit-buttons')
                                <button type="submit" class="btn btn-primary save">{{ __('voyager::generic.save') }}</button>
                            @stop
                            @yield('submit-buttons')
                        </div>
                    </form>

                    <iframe id="form_target" name="form_target" style="display:none"></iframe>
                    <form id="my_form" action="{{ route('voyager.upload') }}" target="form_target" method="post"
                            enctype="multipart/form-data" style="width:0;height:0;overflow:hidden">
                        <input name="image" id="upload_file" type="file"
                                 onchange="$('#my_form').submit();this.value='';">
                        <input type="hidden" name="type_slug" id="type_slug" value="{{ $dataType->slug }}">
                        {{ csrf_field() }}
                    </form>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-danger" id="confirm_delete_modal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><i class="voyager-warning"></i> {{ __('voyager::generic.are_you_sure') }}</h4>
                </div>

                <div class="modal-body">
                    <h4>{{ __('voyager::generic.are_you_sure_delete') }} '<span class="confirm_delete_name"></span>'</h4>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{ __('voyager::generic.cancel') }}</button>
                    <button type="button" class="btn btn-danger" id="confirm_delete">{{ __('voyager::generic.delete_confirm') }}</button>
                </div>
            </div>
        </div>
    </div>
    <!-- End Delete File Modal -->